source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

target 'Jukebox_Example', :exclusive => true do
  pod "Jukebox", :path => "../"
end

target 'Jukebox_Tests', :exclusive => true do
  pod "Jukebox", :path => "../"

  
end
